USE SIGA
GO

CREATE FUNCTION FN_DISCIPLINA_ALUNO(@RA INT)
RETURNS @table TABLE (
CODIGO		        INT,
NOME                varchar(MAX),
SIGLA               VARCHAR (10),
TURNO               CHAR(1),
NUM_AULAS           INT 
)
AS
BEGIN

    INSERT INTO @table(CODIGO ,NOME, SIGLA, TURNO, NUM_AULAS)
    SELECT D.CODIGO, D.NOME, D.SIGLA, D.TURNO, D.NUM_AULAS FROM ALUNO A
    INNER JOIN MATRICULA M
    ON M.RA_ALUNO = A.RA
    INNER JOIN DISCIPLINA D
    ON D.CODIGO = M.CODIGO_DISCIPLINA
    WHERE A.RA = @RA

	RETURN
END